spring:
  application:
    name: loja

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

## Para buscar as informações do usuário no servidor de autenticação
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user

## Para compartilhar o contexto
hystrix:
  shareSecurityContext: true